# Generated by Django 5.1.7 on 2025-03-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
