# Generated by Django 5.1.7 on 2025-03-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
    ]
